Fix for change in virsh behavior
Some versions of virsh fail during basedisk install.

The command:
sudo virsh --connect=qemu:///system list --uuid --name --all
results in:
error: Only one argument from --table, --name and --uuid may be specified.

Observed on Ubuntu 16.04 with virsh 1.3.1.

This patch drops the "--name" option.

Change-Id: I0fbdab3539485430d4a3747fa7f3028bfe6f47ef