[7/7] Add lock_path in neutron.conf
The neutron agents need lock_paths configured. Otherwise, we get
this error:

  RequiredOptError: value required for option lock_path in group [DEFAULT]

Change-Id: I1eb212c502ecee6bf42f4aa32086e5ce0b78fae9